<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('faqs', function (Blueprint $table) {
            $table->id();
            $table->string('question');
            $table->text('answer_beginner');
            $table->text('answer_advance');
            $table->text('answer_tldr');
            $table->string('categories')->default('unknown');
            $table->boolean('highlight')->default(false);
            $table->integer('priority')->default(100); // lower = higher priority
            $table->string('link')->nullable();
            $table->timestamps();
        });

        // Insert initial FAQs
        DB::table('faqs')->insert([
            [
                'question' => 'What is Bitcoin?',
                'answer_beginner' => 'Bitcoin is internet money that lets people send and receive payments without needing a bank. It’s like cash, but fully digital.',
                'answer_advance' => 'Bitcoin is a decentralized digital currency that operates without intermediaries like banks or governments. Transactions are verified by a network of nodes through cryptography and recorded in a public ledger called the blockchain. It allows peer-to-peer value transfer globally with transparency and censorship resistance.',
                'answer_tldr' => 'Digital money that works without banks or governments.',
                'categories' => 'basics,crypto',
                'highlight' => true,
                'priority' => 1,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a block in Bitcoin?',
                'answer_beginner' => 'A block is like a page in Bitcoin’s history book, storing a group of transactions that happened around the same time.',
                'answer_advance' => 'A block is a data structure that contains a batch of validated Bitcoin transactions, along with a reference to the previous block’s hash and a nonce for Proof of Work. Blocks are linked chronologically, forming the blockchain and ensuring data integrity through cryptographic hashing.',
                'answer_tldr' => 'A bundle of transactions added to the blockchain.',
                'categories' => 'basics,blockchain',
                'highlight' => true,
                'priority' => 2,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a Bitcoin transaction?',
                'answer_beginner' => 'A transaction is when someone sends Bitcoin to someone else.',
                'answer_advance' => 'A Bitcoin transaction is a digitally signed record that transfers ownership of Bitcoin from one address to another. It includes inputs, outputs, and is confirmed by the network before being added to the blockchain.',
                'answer_tldr' => 'Transferring Bitcoin from one address to another.',
                'categories' => 'transactions,basics',
                'highlight' => true,
                'priority' => 3,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a Bitcoin miner and what do they do?',
                'answer_beginner' => 'Miners use computers to help keep Bitcoin running by confirming transactions and earning rewards.',
                'answer_advance' => 'Miners are network participants who validate transactions and secure the blockchain by solving complex cryptographic puzzles. This process, called Proof of Work, ensures consensus and results in newly minted Bitcoins and transaction fees as incentives.',
                'answer_tldr' => 'Miners verify transactions and earn Bitcoin.',
                'categories' => 'mining,network',
                'highlight' => false,
                'priority' => 4,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is Proof of Work in Bitcoin?',
                'answer_beginner' => 'It’s a system where miners solve puzzles with computers to keep Bitcoin safe and running.',
                'answer_advance' => 'Proof of Work is a consensus mechanism where miners compete to solve computational puzzles that require significant energy. The first to solve the puzzle adds the next block to the blockchain, ensuring network security and data integrity.',
                'answer_tldr' => 'A puzzle-solving process that secures Bitcoin.',
                'categories' => 'mining,security',
                'highlight' => false,
                'priority' => 5,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'How long do Bitcoin transactions take to confirm?',
                'answer_beginner' => 'It usually takes about 10 minutes for a Bitcoin transaction to go through.',
                'answer_advance' => 'Bitcoin confirmations occur roughly every 10 minutes, as that’s the average time for a new block to be mined. However, actual confirmation time can vary depending on network congestion and the fee attached to the transaction.',
                'answer_tldr' => 'Around 10 minutes, but depends on fees and traffic.',
                'categories' => 'transactions,timing',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What does hash difficulty mean in Bitcoin mining?',
                'answer_beginner' => 'It’s how hard it is for miners to find the next block and earn rewards.',
                'answer_advance' => 'Hash difficulty is a measure of how hard it is to find a valid block hash under Bitcoin’s Proof of Work. It adjusts approximately every 2 weeks to ensure blocks are produced at a consistent interval (~10 minutes), maintaining stability regardless of total mining power.',
                'answer_tldr' => 'A measure of how hard it is to mine a block.',
                'categories' => 'mining,difficulty',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Who is Satoshi Nakamoto, the creator of Bitcoin?',
                'answer_beginner' => 'Bitcoin was made by someone named Satoshi Nakamoto, but nobody knows who they really are.',
                'answer_advance' => 'Satoshi Nakamoto is the pseudonymous creator of Bitcoin, who published the Bitcoin whitepaper in 2008 and launched the software in 2009. Their identity remains unknown, but their invention initiated the decentralized finance revolution.',
                'answer_tldr' => 'Satoshi Nakamoto created Bitcoin in 2009.',
                'categories' => 'basics,history',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Is Bitcoin safe to use?',
                'answer_beginner' => 'Yes, but you have to keep your wallet and password safe.',
                'answer_advance' => 'Bitcoin’s security relies on decentralized consensus, cryptographic algorithms, and economic incentives. The protocol is robust, but individual security depends on practices like using hardware wallets, backing up keys, and avoiding scams.',
                'answer_tldr' => 'Secure by design, but user safety is key.',
                'categories' => 'security,basics',
                'highlight' => true,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Do I need a bank to use Bitcoin?',
                'answer_beginner' => 'No, you can use Bitcoin all by yourself with just a phone or computer.',
                'answer_advance' => 'Bitcoin is designed to operate independently of the traditional banking system. Users can send, receive, and store funds through cryptographic wallets without relying on banks or financial institutions. This allows greater access to financial tools, especially in underserved regions.',
                'answer_tldr' => 'You don’t need a bank to use Bitcoin.',
                'categories' => 'freedom,basics',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I use Bitcoin to pay for everyday things like coffee?',
                'answer_beginner' => 'Yes! Some cafes, online shops, and even restaurants let you pay with Bitcoin — especially in tech-friendly places.',
                'answer_advance' => 'Bitcoin is increasingly accepted by merchants for everyday purchases, including coffee, groceries, and services. In many cases, businesses use point-of-sale apps that convert Bitcoin to local currency instantly, minimizing price volatility. Bitcoin’s growing integration with mobile wallets and the Lightning Network makes it more practical for fast, low-fee payments.',
                'answer_tldr' => 'Yes — Bitcoin can be used for real-world purchases like coffee.',
                'categories' => 'usage,payments',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a cryptocurrency wallet?',
                'answer_beginner' => 'A wallet is an app or device that helps you keep your Bitcoin safe and use it when you want.',
                'answer_advance' => 'A cryptocurrency wallet is a software or hardware tool that stores private keys and manages digital assets. It enables users to sign transactions, view balances, and interact with the blockchain without directly handling the actual coins, which exist only on the network.',
                'answer_tldr' => 'A tool to manage your Bitcoin securely.',
                'categories' => 'wallets,basics',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What makes Bitcoin valuable?',
                'answer_beginner' => 'Bitcoin is special because there’s only a limited amount, and people trust it.',
                'answer_advance' => 'Bitcoin derives value from its fixed supply (21 million coins), decentralization, and resistance to censorship. Its scarcity, security, and increasing adoption contribute to its perception as a store of value, similar to digital gold.',
                'answer_tldr' => 'Scarcity and trust make Bitcoin valuable.',
                'categories' => 'economics,value',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Is Bitcoin legal?',
                'answer_beginner' => 'Yes, Bitcoin is legal in most places. Some countries have different rules about using it, but no one can turn it off or stop the network.',
                'answer_advance' => 'Bitcoin, as a decentralized peer-to-peer protocol, cannot be made illegal in the same way as a centralized entity. While governments can regulate how people access or use Bitcoin — such as taxing it or controlling exchanges — the network itself cannot be shut down or banned. It runs globally on thousands of independent nodes, beyond the control of any single authority.',
                'answer_tldr' => 'The network can’t be banned — only access can be regulated.',
                'categories' => 'regulation,legal',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can Bitcoin be hacked?',
                'answer_beginner' => 'Bitcoin is very secure, but you must protect your wallet and passwords.',
                'answer_advance' => 'The Bitcoin protocol has never been hacked thanks to its decentralized and cryptographic design. However, exchanges, third-party services, or user accounts can be compromised if proper security measures aren’t taken.',
                'answer_tldr' => 'The network is secure; wallets need user protection.',
                'categories' => 'protocol,security,basics',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is the blockchain?',
                'answer_beginner' => 'Blockchain is a public list that keeps track of all Bitcoin transactions.',
                'answer_advance' => 'The blockchain is a decentralized, cryptographic ledger that permanently records Bitcoin transactions. Each block contains a batch of transactions and links to the previous block, ensuring data integrity and security.',
                'answer_tldr' => 'A secure, public history of all Bitcoin activity.',
                'categories' => 'blockchain,basics',
                'highlight' => true,
                'priority' => 90,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What are Bitcoin fees?',
                'answer_beginner' => 'You pay a small fee so miners can confirm your transaction.',
                'answer_advance' => 'Bitcoin transaction fees are optional payments that encourage miners to prioritize a transaction for inclusion in the next block. Higher fees can result in faster confirmation, especially during periods of network congestion.',
                'answer_tldr' => 'Fees help confirm your Bitcoin transaction faster.',
                'categories' => 'transactions,fees,mining',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can governments ban Bitcoin?',
                'answer_beginner' => 'Governments can try to stop people from using Bitcoin, but they can’t shut it down completely.',
                'answer_advance' => 'Governments can regulate exchanges or restrict access to Bitcoin-related services within their borders. However, Bitcoin’s decentralized architecture, with thousands of independent nodes, makes it extremely difficult to shut down entirely.',
                'answer_tldr' => 'Governments can restrict access, not stop Bitcoin itself.',
                'categories' => 'regulation,freedom',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I reverse a Bitcoin transaction?',
                'answer_beginner' => 'No. Once you send Bitcoin, you can’t undo it.',
                'answer_advance' => 'Bitcoin transactions are irreversible once confirmed by the network. This immutability ensures security and trustlessness, but it also means users must double-check details before sending.',
                'answer_tldr' => 'No — Bitcoin transactions are permanent.',
                'categories' => 'transactions,basics',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'How many Bitcoins exist?',
                'answer_beginner' => 'There will only ever be 21 million Bitcoins in total.',
                'answer_advance' => 'Bitcoin’s protocol limits the total supply to 21 million coins. New coins are created through mining and released gradually, with rewards halving approximately every four years, reducing issuance over time.',
                'answer_tldr' => 'Bitcoin has a fixed supply: 21 million coins.',
                'categories' => 'supply,economics',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I earn Bitcoin without buying it?',
                'answer_beginner' => 'Yes! You can get Bitcoin by working or accepting it for things you sell.',
                'answer_advance' => 'Bitcoin can be earned by selling goods or services, participating in freelance jobs that pay in crypto, mining, joining earn-to-learn programs, or using platforms that offer Bitcoin rewards or interest (with associated risks).',
                'answer_tldr' => 'Yes — work, sell, or mine to earn Bitcoin.',
                'categories' => 'earn,income',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is the Bitcoin halving?',
                'answer_beginner' => 'It’s when the reward for miners is cut in half, which happens every few years.',
                'answer_advance' => 'Bitcoin halving is a built-in event that reduces the block reward miners receive by 50% every 210,000 blocks (~every 4 years). It controls new Bitcoin issuance and increases scarcity, often influencing market dynamics.',
                'answer_tldr' => 'Miner rewards are cut in half every 4 years.',
                'categories' => 'supply,economics,halving',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://www.kraken.com/learn/what-is-bitcoin-halving',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a Bitcoin node?',
                'answer_beginner' => 'A node is a computer that helps keep the Bitcoin network running safely.',
                'answer_advance' => 'A Bitcoin node runs the full Bitcoin protocol and helps validate and relay transactions and blocks. Full nodes maintain the entire blockchain and enforce the network’s consensus rules, ensuring trustless operation.',
                'answer_tldr' => 'A computer that checks transactions and enforces Bitcoin’s rules.',
                'categories' => 'network,basics,nodes',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://bitcoin.org/en/full-node',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Why is Bitcoin considered decentralized?',
                'answer_beginner' => 'Because nobody owns or controls it — lots of computers run it together.',
                'answer_advance' => 'Bitcoin is decentralized because it runs on a global, permissionless network of nodes and miners. Decisions are made by consensus among participants, not by a central party. This structure prevents censorship and control.',
                'answer_tldr' => 'Bitcoin is run by many — not controlled by anyone.',
                'categories' => 'decentralization,freedom',
                'highlight' => false,
                'priority' => 90,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I send Bitcoin to anyone in the world?',
                'answer_beginner' => 'Yes! You can send Bitcoin to anyone, anywhere in the world.',
                'answer_advance' => 'Bitcoin enables global, peer-to-peer transfers without needing permission from intermediaries. As long as both sender and recipient have access to the internet and a wallet, they can transact directly, regardless of borders.',
                'answer_tldr' => 'Yes — fast, borderless payments.',
                'categories' => 'basics,transactions,freedom',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a Bitcoin address?',
                'answer_beginner' => 'It’s like your home address for Bitcoin — where people can send you coins.',
                'answer_advance' => 'A Bitcoin address is an alphanumeric string derived from your public key, used as the receiving end of a transaction. It’s not tied to your identity and allows others to send you Bitcoin.',
                'answer_tldr' => 'A unique code used to receive Bitcoin.',
                'categories' => 'wallets,basics',
                'highlight' => true,
                'priority' => 100,
                'link' => 'https://en.bitcoin.it/wiki/Address',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is the Lightning Network?',
                'answer_beginner' => 'It’s a special upgrade that lets you send Bitcoin faster and cheaper.',
                'answer_advance' => 'The Lightning Network is a second-layer solution built on top of the Bitcoin blockchain. It enables off-chain, peer-to-peer transactions using payment channels, which significantly reduce cost and improve transaction speed while maintaining security.',
                'answer_tldr' => 'A fast, low-cost payment layer for Bitcoin.',
                'categories' => 'scaling,lightning,tech',
                'highlight' => false,
                'priority' => 90,
                'link' => 'https://lightning.network/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Is Bitcoin bad for the environment?',
                'answer_beginner' => 'Bitcoin uses energy, which worries some people. But a lot of that energy now comes from clean or leftover sources, so it’s not always as bad as it seems.',
                'answer_advance' => 'Bitcoin’s Proof of Work system requires energy to secure the network, which leads to concerns about environmental impact. However, the true effect depends heavily on the energy sources used. Many miners already rely on renewable, surplus, or stranded energy. Compared to industries like gold mining or banking, Bitcoin’s footprint can be relatively efficient — but whether it’s "bad" depends on your point of reference and values.',
                'answer_tldr' => 'It depends on the type of energy miners use and what you compare it to.',
                'categories' => 'mining,environment,energy',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Is Bitcoin anonymous or traceable?',
                'answer_beginner' => 'Not exactly. Your name isn’t shown, but everyone can see your Bitcoin transactions on a public record called the blockchain.',
                'answer_advance' => 'Bitcoin is pseudonymous, not anonymous. Every transaction is publicly recorded on the blockchain, and while wallet addresses don’t include personal info, they can often be linked to real identities through exchanges, IP addresses, or behavioral patterns. Advanced techniques like chain analysis are used to trace activity. That said, tools like privacy wallets, CoinJoin, and the Lightning Network can improve transactional privacy.',
                'answer_tldr' => 'Bitcoin is traceable — unless extra privacy steps are taken.',
                'categories' => 'privacy,basics',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://en.bitcoin.it/wiki/Anonymity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I use Bitcoin on my phone?',
                'answer_beginner' => 'Yes! You can use an app to send and receive Bitcoin easily.',
                'answer_advance' => 'Yes. Mobile wallets like Muun, Phoenix, and BlueWallet provide secure, user-friendly access to Bitcoin. They support sending, receiving, and even Lightning payments directly from your smartphone.',
                'answer_tldr' => 'Yes — use a mobile wallet app.',
                'categories' => 'wallets,mobile,apps',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a Bitcoin fork?',
                'answer_beginner' => 'A fork is when Bitcoin changes — it can make a new version or just update the old one.',
                'answer_advance' => 'A Bitcoin fork happens when changes are made to the protocol rules. Soft forks are backward-compatible updates, while hard forks create a new version of the chain and often result in a separate cryptocurrency. Forks reflect community disagreements or upgrades.',
                'answer_tldr' => 'A change that may split Bitcoin into two paths.',
                'categories' => 'protocol,forks,history',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://en.bitcoin.it/wiki/Fork_(disambiguation)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What happens if I lose my Bitcoin wallet or keys?',
                'answer_beginner' => 'If you lose your wallet or recovery phrase and don’t have a backup, you won’t be able to get your Bitcoin back — it’s like losing cash with no way to recover it.',
                'answer_advance' => 'Bitcoin is secured by cryptographic private keys. If you lose access to your wallet and don’t have your private key or seed phrase backed up, your Bitcoin is permanently lost. There is no central authority or “forgot password” option — control of your keys is what defines ownership. This makes proper backups and secure storage essential.',
                'answer_tldr' => 'Lose your keys, lose your Bitcoin — permanently.',
                'categories' => 'security,basics,keys',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a private key?',
                'answer_beginner' => 'It’s a secret code that unlocks your Bitcoin and lets you use it.',
                'answer_advance' => 'A private key is a cryptographic string that proves ownership of Bitcoin in a wallet. Whoever controls the private key can spend the associated funds. Keeping it secure is critical to preventing loss or theft.',
                'answer_tldr' => 'Your secret code that controls your Bitcoin.',
                'categories' => 'wallets,security,keys',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://en.bitcoin.it/wiki/Private_key',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What happens if the internet goes down?',
                'answer_beginner' => 'Bitcoin needs the internet to work, but if it goes down, you can wait or use special tools to send transactions later.',
                'answer_advance' => 'Bitcoin generally relies on the internet for broadcasting transactions. However, solutions like Blockstream Satellite, mesh networks (e.g. Locha Mesh), or radio communication allow Bitcoin data to move without traditional internet, enhancing resilience during outages or censorship.',
                'answer_tldr' => 'Bitcoin can still work using satellites or offline networks.',
                'categories' => 'infrastructure,resilience,network',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://blockstream.com/satellite/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Why is there a 21 million limit?',
                'answer_beginner' => 'Bitcoin has a limit so no one can make unlimited coins — like printing money.',
                'answer_advance' => 'Bitcoin’s fixed supply of 21 million coins was designed to mimic scarce assets like gold and prevent inflation. It introduces predictable monetary policy where issuance is transparent and mathematically enforced through code.',
                'answer_tldr' => 'Bitcoin is scarce by design — only 21 million will exist.',
                'categories' => 'supply,economics,design',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a seed phrase?',
                'answer_beginner' => 'It’s a secret list of words that helps you recover your Bitcoin wallet if your phone or computer is lost. Keep it safe!',
                'answer_advance' => 'A seed phrase (12–24 words) is a human-readable backup of your entire Bitcoin wallet. It derives your private keys using standards like BIP39 and should be stored offline in secure locations. If compromised, your funds can be stolen; if lost, they are unrecoverable.',
                'answer_tldr' => 'A secret backup of your wallet — never lose or share it.',
                'categories' => 'wallets,security,backup',
                'highlight' => false,
                'priority' => 95,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a hardware wallet?',
                'answer_beginner' => 'It’s a small device that keeps your Bitcoin safe, even if your phone gets hacked.',
                'answer_advance' => 'A hardware wallet stores your private keys in a secure, offline environment. It allows signing transactions safely even on compromised devices. Popular options include Trezor and Ledger.',
                'answer_tldr' => 'A secure device that protects your Bitcoin offline.',
                'categories' => 'wallets,security,hardware',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What does "not your keys, not your coins" mean?',
                'answer_beginner' => 'If you don’t have the key, you don’t really own the Bitcoin.',
                'answer_advance' => 'This phrase warns users that holding Bitcoin on custodial platforms means giving up control. True ownership only exists when you control your own private keys — otherwise, your funds can be frozen or lost.',
                'answer_tldr' => 'Without your keys, you don’t control the Bitcoin.',
                'categories' => 'security,ownership,basics',
                'highlight' => false,
                'priority' => 90,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Why is Bitcoin considered programmable money?',
                'answer_beginner' => 'Bitcoin lets you set special rules — like who can spend it or when.',
                'answer_advance' => 'Bitcoin supports programmable spending conditions through its scripting language. You can create multisig wallets, timelocks, or custom access rules. Combined with tools like PSBTs and Miniscript, Bitcoin enables trustless, automated financial logic.',
                'answer_tldr' => 'Bitcoin lets you automate spending rules on-chain.',
                'categories' => 'programmability,scripting,tech',
                'highlight' => false,
                'priority' => 90,
                'link' => 'https://chemaclass.com/blog/programmable-money/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What are satoshis?',
                'answer_beginner' => 'Satoshis, or "sats", are tiny pieces of Bitcoin. Just like cents are smaller parts of a dollar, satoshis are smaller parts of a Bitcoin.',
                'answer_advance' => 'A satoshi is the smallest unit of Bitcoin, named after its creator, Satoshi Nakamoto. One Bitcoin is equal to 100,000,000 satoshis. They make it easier to price everyday items and support microtransactions, especially as Bitcoin’s price grows.',
                'answer_tldr' => 'The smallest unit of Bitcoin — 1 BTC = 100 million sats.',
                'categories' => 'basics,units',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://en.bitcoin.it/wiki/Units',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    public function down(): void
    {
        Schema::dropIfExists('faqs');
    }
};
