<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('faqs', function (Blueprint $table) {
            $table->id();
            $table->string('question');
            $table->text('answer_beginner');
            $table->text('answer_advance');
            $table->text('answer_tldr');
            $table->string('categories')->default('unknown');
            $table->boolean('highlight')->default(false);
            $table->integer('priority')->default(100); // lower = higher priority
            $table->string('link')->nullable();
            $table->timestamps();
        });

        // Insert initial FAQs
        DB::table('faqs')->insert([
            [
                'question' => 'What is Bitcoin?',
                'answer_beginner' => 'Bitcoin is digital money that you can send and receive over the internet without using a bank or government.',
                'answer_advance' => 'Bitcoin is a digital form of money that works without banks or governments. It allows people anywhere in the world to send and receive payments over the internet directly — securely, quickly, and without needing permission from a central authority. Bitcoin is powered by a public network called the blockchain, which ensures every transaction is verified and recorded.',
                'answer_tldr' => 'A digital currency that works without banks or governments.',
                'categories' => 'basics,crypto',
                'highlight' => true,
                'priority' => 1,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a block?',
                'answer_beginner' => 'A block is like a page in Bitcoin’s public record book. It collects and stores a bunch of transactions that happened around the same time. When the block is full, it gets added to the end of the blockchain — which is a long chain of these blocks — helping everyone agree on who sent and received Bitcoin. This system keeps everything organized, secure, and impossible to change after it’s added.',
                'answer_advance' => 'A block is a structured data unit in the Bitcoin blockchain that records a set of validated transactions, a reference to the previous block’s hash, a timestamp, and other metadata like the nonce used for Proof of Work. Blocks serve as the building units of the blockchain. By cryptographically linking to the previous block, each new block reinforces the integrity of the entire chain. This design ensures immutability, consensus, and chronological ordering of transactions across the decentralized network. New blocks are mined approximately every 10 minutes and once added, their contents are practically irreversible.',
                'answer_tldr' => 'A container of Bitcoin transactions added to the blockchain.',
                'categories' => 'basics,blockchain',
                'highlight' => true,
                'priority' => 2,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a transaction?',
                'answer_beginner' => 'A transaction is when someone sends Bitcoin to another person.',
                'answer_advance' => 'A Bitcoin transaction is the process of sending Bitcoin from one wallet address to another. Each transaction is recorded on the blockchain — a public ledger — and includes details like the sender, receiver, and amount (without revealing personal identities). Once confirmed by the network, the transaction becomes permanent and tamper-proof.',
                'answer_tldr' => 'Sending Bitcoin from one address to another.',
                'categories' => 'transactions,basics',
                'highlight' => true,
                'priority' => 3,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a miner?',
                'answer_beginner' => 'A miner uses a computer to confirm Bitcoin transactions and earn rewards.',
                'answer_advance' => 'A miner is a participant in the Bitcoin network who uses computers to verify transactions and add them to the blockchain. To do this, miners solve complex cryptographic puzzles — a process called proof of work. The first miner to solve the puzzle gets to add the next block and earns a Bitcoin reward in return.',
                'answer_tldr' => 'Miners confirm transactions and secure the blockchain.',
                'categories' => 'mining,network',
                'highlight' => false,
                'priority' => 4,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is Proof of Work?',
                'answer_beginner' => 'Proof of Work is a system where miners solve complex puzzles to secure Bitcoin.',
                'answer_advance' => 'Proof of Work is the system that keeps Bitcoin secure and decentralized. It’s a consensus mechanism that requires miners to use powerful computers to solve complex math problems. The first to solve the puzzle earns the right to add the next block to the blockchain and receives a reward. This process makes it very difficult to cheat, helping ensure that all transactions are honest and verified by the network.',
                'answer_tldr' => 'Miners solve puzzles to add blocks and secure the network.',
                'categories' => 'mining,security',
                'highlight' => false,
                'priority' => 5,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'How long does it take to confirm a transaction?',
                'answer_beginner' => 'Bitcoin transactions are usually confirmed every 10 minutes.',
                'answer_advance' => 'On average, Bitcoin transactions are confirmed every 10 minutes — that’s how often a new block is added to the blockchain. However, the exact time can vary depending on how busy the network is and how much fee you attach to your transaction. Higher fees are usually confirmed faster, while low-fee transactions may wait longer or even be delayed.',
                'answer_tldr' => 'Typically around 10 minutes, but varies with fees and traffic.',
                'categories' => 'transactions,timing',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is hash difficulty?',
                'answer_beginner' => 'Hash difficulty measures how hard it is to find a valid block when mining Bitcoin.',
                'answer_advance' => 'It’s how hard the Bitcoin network makes it to "win" the right to add a new block. The more people mining, the harder it gets — so that a block is still found about every 10 minutes.',
                'answer_tldr' => 'Hash difficulty controls how hard it is to mine a new block.',
                'categories' => 'mining,difficulty',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Who created Bitcoin?',
                'answer_beginner' => 'Bitcoin was created by someone using the name Satoshi Nakamoto in 2009.',
                'answer_advance' => 'Bitcoin was created by someone using the name Satoshi Nakamoto in 2009. Their true identity is still unknown, but their invention started a global movement for decentralized digital money.',
                'answer_tldr' => 'Satoshi Nakamoto created Bitcoin in 2009.',
                'categories' => 'basics,history',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Is Bitcoin real money?',
                'answer_beginner' => 'Yes, Bitcoin can be used to pay for things and transfer value.',
                'answer_advance' => 'Yes. Bitcoin can be used to pay for products, services, or even send money across the world — just like traditional currencies, but digitally and without banks.',
                'answer_tldr' => 'Yes, Bitcoin works as digital money.',
                'categories' => 'basics,currency',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Is Bitcoin safe?',
                'answer_beginner' => 'Bitcoin’s technology is secure, but users must keep their wallets and keys safe.',
                'answer_advance' => 'Bitcoin’s technology is incredibly secure, thanks to cryptography and a decentralized network of thousands of computers. But like cash, you’re responsible for keeping it safe. If you lose your private keys or fall for a scam, there’s no bank to recover your funds. That’s why using trusted wallets, strong passwords, and good security practices is essential.',
                'answer_tldr' => 'Bitcoin is secure, but your safety depends on how you use it.',
                'categories' => 'security,basics',
                'highlight' => true,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'How does Bitcoin work?',
                'answer_beginner' => 'Bitcoin uses a network of computers to verify and record transactions.',
                'answer_advance' => 'Bitcoin is a digital currency powered by a global network of computers. When someone sends Bitcoin, the transaction is broadcast to the network, verified by participants, and added to a chain of blocks called the blockchain. This system ensures that transactions are transparent, tamper-proof, and don’t require any central authority to function.',
                'answer_tldr' => 'Bitcoin works using a decentralized network and the blockchain.',
                'categories' => 'basics,technology',
                'highlight' => true,
                'priority' => 10,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Do I need a bank to use Bitcoin?',
                'answer_beginner' => 'No. You can use Bitcoin without a bank.',
                'answer_advance' => 'Not at all. Bitcoin was designed to work outside of traditional banking systems. You can create a wallet, store funds, and make payments without needing approval from any institution. This gives people more financial freedom and access, especially in places where banking services are limited or unreliable.',
                'answer_tldr' => 'Bitcoin works without banks — it’s peer-to-peer.',
                'categories' => 'freedom,basics',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I buy a coffee with Bitcoin?',
                'answer_beginner' => 'Yes, some shops and cafes accept Bitcoin.',
                'answer_advance' => 'You can in some places! A growing number of cafes, restaurants, and retailers accept Bitcoin, especially in tech-forward cities. You can also use payment apps that instantly convert Bitcoin into local currency at checkout.',
                'answer_tldr' => 'Yes, in some places you can spend Bitcoin directly.',
                'categories' => 'usage,payments',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a cryptocurrency wallet?',
                'answer_beginner' => 'A wallet is a tool to store and use your Bitcoin securely.',
                'answer_advance' => 'A cryptocurrency wallet is a digital tool that lets you store, send, and receive Bitcoin securely. It doesn’t actually hold coins like a physical wallet — instead, it manages the private keys that give you access to your crypto on the blockchain.',
                'answer_tldr' => 'A wallet lets you store and manage your Bitcoin.',
                'categories' => 'wallets,basics',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What makes Bitcoin valuable?',
                'answer_beginner' => 'Bitcoin is valuable because it’s limited and people trust it.',
                'answer_advance' => 'Bitcoin is valuable because it is scarce, secure, and decentralized. Its supply is limited to 21 million coins, making it resistant to inflation. It operates without central control, giving users freedom and transparency. Like gold, its value also grows as more people believe in its usefulness and adopt it.',
                'answer_tldr' => 'Scarcity, trust, and decentralization make Bitcoin valuable.',
                'categories' => 'economics,value',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Is Bitcoin legal?',
                'answer_beginner' => 'Yes, Bitcoin is legal in most countries, though rules vary.',
                'answer_advance' => 'While governments can regulate how people access or use Bitcoin (such as through exchanges), they can’t shut it down, because no one controls the network. This resilience and independence are what give Bitcoin its true power and global potential. Bitcoin can be regulated — but not turned off. Its decentralized design makes it unstoppable.',
                'answer_tldr' => 'Bitcoin can be regulated — but not shut down.',
                'categories' => 'regulation,legal',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can Bitcoin be hacked?',
                'answer_beginner' => 'Bitcoin itself is very secure, but users must protect their wallets from hackers.',
                'answer_advance' => 'The Bitcoin network has never been hacked due to its robust cryptographic and decentralized structure. However, exchanges and individual wallets can be vulnerable if not secured properly by the user.',
                'answer_tldr' => 'Bitcoin is secure, but your wallet can be hacked if not protected.',
                'categories' => 'security,basics',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can Bitcoin be traced?',
                'answer_beginner' => 'Yes, Bitcoin transactions are public and can be traced on the blockchain.',
                'answer_advance' => 'Bitcoin is pseudonymous, not anonymous. All transactions are recorded on a public ledger. While wallet addresses don’t reveal names, with enough data they can sometimes be linked to real identities.',
                'answer_tldr' => 'Yes — transactions are public and traceable.',
                'categories' => 'privacy,transactions',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is the blockchain?',
                'answer_beginner' => 'The blockchain is a public record that shows all Bitcoin transactions.',
                'answer_advance' => 'The blockchain is a decentralized, append-only ledger where Bitcoin transactions are permanently stored in blocks. Each block references the previous one, creating a secure and tamper-evident chain.',
                'answer_tldr' => 'A public ledger of all Bitcoin activity.',
                'categories' => 'blockchain,basics',
                'highlight' => true,
                'priority' => 90,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What happens if I lose my wallet?',
                'answer_beginner' => 'If you lose your wallet and don’t have a backup, your Bitcoin is gone.',
                'answer_advance' => 'Losing your wallet without access to the private keys or recovery phrase means the funds are permanently lost. There’s no central authority to restore your access.',
                'answer_tldr' => 'No backup = funds lost forever.',
                'categories' => 'wallets,safety',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What are Bitcoin fees?',
                'answer_beginner' => 'Bitcoin fees are small amounts you pay to get your transaction confirmed.',
                'answer_advance' => 'Bitcoin transaction fees are paid to incentivize miners to include your transaction in the next block. Fees are dynamic and based on transaction size and network congestion.',
                'answer_tldr' => 'Small fees to get your transaction confirmed.',
                'categories' => 'transactions,fees',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can governments ban Bitcoin?',
                'answer_beginner' => 'Governments can try to stop people from using Bitcoin, but they can’t stop the network.',
                'answer_advance' => 'While governments can restrict access to exchanges or penalize usage, Bitcoin’s decentralized nature makes it censorship-resistant. It runs globally on thousands of independent nodes.',
                'answer_tldr' => 'They can restrict it, but not stop it.',
                'categories' => 'regulation,freedom',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I reverse a Bitcoin transaction?',
                'answer_beginner' => 'No. Once a transaction is sent, it can’t be reversed.',
                'answer_advance' => 'Bitcoin transactions are final and irreversible once confirmed. This is by design to avoid fraud and ensure trustless settlement. Always double-check the recipient address.',
                'answer_tldr' => 'No — all transactions are final.',
                'categories' => 'transactions,basics',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'How many Bitcoins exist?',
                'answer_beginner' => 'There will only ever be 21 million Bitcoins.',
                'answer_advance' => 'Bitcoin’s code enforces a hard cap of 21 million coins. New bitcoins are created through mining and the issuance halves roughly every 4 years, slowing over time.',
                'answer_tldr' => '21 million maximum.',
                'categories' => 'supply,economics',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I earn Bitcoin without buying it?',
                'answer_beginner' => 'Yes. You can earn Bitcoin by working, mining, or accepting it as payment.',
                'answer_advance' => 'You can earn Bitcoin by offering services, selling goods, participating in "earn" programs, mining, or even earning interest on holdings via certain platforms (with risk).',
                'answer_tldr' => 'Yes — work, sell, or mine for it.',
                'categories' => 'earn,income',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is the Bitcoin halving?',
                'answer_beginner' => 'Bitcoin halving is when the reward miners get is cut in half, happening about every 4 years.',
                'answer_advance' => 'Bitcoin halving is a programmed event that reduces the block reward miners receive by 50%, occurring every 210,000 blocks (~4 years). It controls inflation and leads to scarcity over time.',
                'answer_tldr' => 'Every ~4 years, miner rewards are cut in half.',
                'categories' => 'supply,economics,halving',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://www.kraken.com/learn/what-is-bitcoin-halving',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a Bitcoin node?',
                'answer_beginner' => 'A node is a computer that helps keep Bitcoin running by checking transactions.',
                'answer_advance' => 'A Bitcoin node is software that participates in the Bitcoin network by validating blocks and transactions. Full nodes store the entire blockchain and enforce protocol rules.',
                'answer_tldr' => 'A computer that checks and supports Bitcoin’s rules.',
                'categories' => 'network,basics,nodes',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://bitcoin.org/en/full-node',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Why is Bitcoin considered decentralized?',
                'answer_beginner' => 'Because no single person or company controls it.',
                'answer_advance' => 'Bitcoin is decentralized because it runs on a global network of independent computers. No central authority can alter its rules, stop transactions, or print more Bitcoin.',
                'answer_tldr' => 'No one controls it — it’s run by many computers.',
                'categories' => 'decentralization,freedom',
                'highlight' => false,
                'priority' => 90,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I send Bitcoin to anyone in the world?',
                'answer_beginner' => 'Yes! You can send Bitcoin to anyone, anywhere.',
                'answer_advance' => 'Yes. Bitcoin transactions are borderless. Anyone with a wallet and internet connection can receive Bitcoin, without approval from banks or governments.',
                'answer_tldr' => 'Yes — globally and instantly.',
                'categories' => 'basics,transactions,freedom',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a Bitcoin address?',
                'answer_beginner' => 'It’s like an email for Bitcoin — where you receive coins.',
                'answer_advance' => 'A Bitcoin address is a string of letters and numbers that acts like a destination for receiving Bitcoin. It’s derived from a public key and has no identity attached.',
                'answer_tldr' => 'A place to receive Bitcoin, like an email address.',
                'categories' => 'wallets,basics',
                'highlight' => true,
                'priority' => 100,
                'link' => 'https://en.bitcoin.it/wiki/Address',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is the Lightning Network?',
                'answer_beginner' => 'It’s a way to send Bitcoin faster and cheaper.',
                'answer_advance' => 'The Lightning Network is a second-layer protocol on top of Bitcoin. It allows off-chain transactions between parties, enabling near-instant and low-cost payments.',
                'answer_tldr' => 'A faster way to send Bitcoin using a layer on top.',
                'categories' => 'scaling,lightning,tech',
                'highlight' => false,
                'priority' => 90,
                'link' => 'https://lightning.network/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Is Bitcoin bad for the environment?',
                'answer_beginner' => 'No — it depends on how you look at it. Bitcoin mining does use energy, but many miners are moving toward renewable sources. Compared to some industries, it may not be as harmful as people think.',
                'answer_advance' => 'No, not inherently. The environmental impact of Bitcoin mining depends on how its energy use is sourced and what you’re comparing it to. Bitcoin’s proof-of-work system uses electricity to secure the network, but critics often overlook that many miners already use renewable or stranded energy. Also, unlike many high-energy industries (like banking or gold mining), Bitcoin provides a permissionless global monetary system. Whether that energy use is “bad” depends on the values and trade-offs you prioritize.',
                'answer_tldr' => 'Not necessarily — it depends how you measure it.',
                'categories' => 'mining,environment,energy',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I use Bitcoin anonymously?',
                'answer_beginner' => 'It’s not totally anonymous — your activity is public.',
                'answer_advance' => 'Bitcoin is pseudonymous. All transactions are recorded publicly, but don’t show names. Tools like mixers and privacy wallets can increase anonymity, but nothing guarantees full privacy.',
                'answer_tldr' => 'Not private by default — but pseudonymous.',
                'categories' => 'privacy,basics',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://en.bitcoin.it/wiki/Anonymity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I use Bitcoin on my phone?',
                'answer_beginner' => 'Yes. You can use Bitcoin apps on your phone.',
                'answer_advance' => 'Many mobile wallets like Muun, BlueWallet, and Phoenix allow you to send, receive, and manage Bitcoin from your smartphone. They often support QR codes, backups, and even Lightning.',
                'answer_tldr' => 'Yes — use a wallet app.',
                'categories' => 'wallets,mobile,apps',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a Bitcoin fork?',
                'answer_beginner' => 'A Bitcoin fork is when the network changes and creates a new version of Bitcoin. Sometimes the change is small, and everything keeps working together. Other times, it creates a new and separate type of Bitcoin.',
                'answer_advance' => 'A Bitcoin fork occurs when there’s a change in the network rules. There are two types: soft forks and hard forks. A soft fork is backward-compatible — older nodes still recognize the new blocks, so the chain remains unified. A hard fork, however, is not backward-compatible and creates a permanent split in the blockchain, resulting in a separate chain and currency. Forks often happen when developers or miners disagree on how Bitcoin should evolve.',
                'answer_tldr' => 'A split into a new version of Bitcoin.',
                'categories' => 'protocol,forks,history',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://en.bitcoin.it/wiki/Fork_(disambiguation)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I lose my Bitcoin?',
                'answer_beginner' => 'Yes, if you lose your wallet or keys, your Bitcoin is gone forever.',
                'answer_advance' => 'Yes. Bitcoin ownership is based on cryptographic keys. If you lose your private key or recovery phrase and don’t have a backup, there’s no way to access your coins.',
                'answer_tldr' => 'Yes — losing your keys means losing your Bitcoin.',
                'categories' => 'security,basics,keys',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a private key?',
                'answer_beginner' => 'It’s a secret code that lets you spend your Bitcoin.',
                'answer_advance' => 'A private key is a long alphanumeric string that gives you full control over the Bitcoin in a corresponding address. If someone else gets your private key, they can steal your funds.',
                'answer_tldr' => 'Your secret password to access Bitcoin.',
                'categories' => 'wallets,security,keys',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://en.bitcoin.it/wiki/Private_key',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What happens if the internet goes down?',
                'answer_beginner' => 'Bitcoin needs the internet, but transactions can wait or use workarounds.',
                'answer_advance' => 'While Bitcoin generally relies on internet access, offline tools, satellites, and mesh networks like Blockstream Satellite or Locha Mesh can transmit transactions without regular internet.',
                'answer_tldr' => 'Bitcoin can adapt using satellites or offline tools.',
                'categories' => 'infrastructure,resilience,network',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://blockstream.com/satellite/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can governments ban Bitcoin?',
                'answer_beginner' => 'They can try, but Bitcoin doesn’t need permission to work.',
                'answer_advance' => 'Governments can restrict access to exchanges or try to discourage use, but they can’t shut down the Bitcoin network due to its decentralized, peer-to-peer design.',
                'answer_tldr' => 'They can’t stop the network, only regulate access.',
                'categories' => 'regulation,freedom,government',
                'highlight' => false,
                'priority' => 95,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Why is there a 21 million limit?',
                'answer_beginner' => 'Bitcoin has a cap to stop inflation.',
                'answer_advance' => 'The 21 million cap was designed by Satoshi Nakamoto to create scarcity and ensure predictable monetary policy. It mimics gold’s scarcity and makes Bitcoin deflationary over time.',
                'answer_tldr' => 'Limited supply = scarcity = value.',
                'categories' => 'supply,economics,design',
                'highlight' => false,
                'priority' => 100,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What are Bitcoin fees?',
                'answer_beginner' => 'You pay a small fee to send Bitcoin.',
                'answer_advance' => 'Fees are paid to miners to include your transaction in a block. They vary based on network congestion and transaction size. Higher fees get faster confirmations.',
                'answer_tldr' => 'Fees help miners process your transaction.',
                'categories' => 'transactions,fees,mining',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://mempool.space/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a seed phrase?',
                'answer_beginner' => 'A seed phrase is a short list of simple words (like apple, river, yellow) that works like a secret backup key to your Bitcoin wallet. If your phone or computer gets lost or broken, you can use this phrase to recover your Bitcoin on a new device. But be very careful: anyone who has your seed phrase can take your Bitcoin. That’s why you should never share it and keep it written down in a safe place — not on your phone or online.',
                'answer_advance' => 'A seed phrase, also called a recovery phrase or mnemonic phrase, is a human-readable sequence of 12 to 24 words that encodes the entropy used to generate all your private keys, public keys, and addresses in a deterministic (HD) wallet. It acts as the root of your entire wallet structure. BIP39 defines how the words are chosen and mapped to binary entropy, while BIP32/BIP44 define how keys are derived from it hierarchically. Because it represents full access to your funds, securing the seed phrase is paramount — it should be written down and stored offline, ideally in multiple secure locations. If someone else obtains your seed phrase, they can fully control your funds, regardless of wallet or device. Conversely, if you lose the phrase and your device is destroyed or wiped, there’s no way to recover your Bitcoin. It is the single point of recovery and vulnerability.',
                'answer_tldr' => 'A backup of your wallet — never share it.',
                'categories' => 'wallets,security,backup',
                'highlight' => false,
                'priority' => 95,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What is a hardware wallet?',
                'answer_beginner' => 'It’s a special device to keep your Bitcoin safe.',
                'answer_advance' => 'A hardware wallet stores your private keys offline in a secure physical device. It adds a strong layer of protection against malware, phishing, and remote hacking.',
                'answer_tldr' => 'A physical device to store Bitcoin securely.',
                'categories' => 'wallets,security,hardware',
                'highlight' => false,
                'priority' => 100,
                'link' => 'https://trezor.io/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What does "not your keys, not your coins" mean?',
                'answer_beginner' => 'If you don’t control your wallet keys, your Bitcoin isn’t really yours.',
                'answer_advance' => 'It means that holding Bitcoin on centralized platforms (like exchanges) gives them control over your coins. Only by holding your own private keys do you have true ownership.',
                'answer_tldr' => 'If someone else holds the keys, they own the Bitcoin.',
                'categories' => 'security,ownership,basics',
                'highlight' => false,
                'priority' => 90,
                'link' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Why is Bitcoin considered programmable money?',
                'answer_beginner' => 'Because Bitcoin lets you set special rules for how coins can be spent. For example, you can make a transaction that only works after a certain date, or that needs multiple people to sign. These rules are built into Bitcoin’s design.',
                'answer_advance' => 'Bitcoin is considered programmable money because it allows transactions to include programmable conditions through its built-in scripting system. This makes it possible to define how and when coins can be spent. With Bitcoin Script, users can require multiple signatures (multisig), set time-based conditions (timelocks like CheckLockTimeVerify or CheckSequenceVerify), or build logic for things like escrow, inheritance schemes, or spending delays. This programmable layer exists at the protocol level, and when combined with external tools (like PSBTs or miniscript), enables expressive, auditable, and secure monetary logic — without needing third-party intermediaries. In essence, Bitcoin enables self-enforcing contracts that live on-chain, embodying the true meaning of programmable money.',
                'answer_tldr' => 'Bitcoin lets you add rules to how money can be spent — like delays or approvals.',
                'categories' => 'programmability,scripting,tech',
                'highlight' => false,
                'priority' => 90,
                'link' => 'https://chemaclass.com/blog/programmable-money/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    public function down(): void
    {
        Schema::dropIfExists('faqs');
    }
};
